name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
      - name: Set up just
        uses: extractions/setup-just@v3
      - name: Install Wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
      - name: Build the project
        run: just build
      - name: Run tests
        run: npm test
      - name: Run format checks
        run: npm run format-ci
      - name: Run ESLint
        run: npm run lint
